# Generated by Django 4.1.6 on 2023-03-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='nombre',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='nombre',
            field=models.CharField(default='', max_length=20),
        ),
    ]
