# Generated by Django 4.1.6 on 2023-04-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_pedidos_nombre_alter_solicitudes_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isb', models.CharField(default='', max_length=20)),
                ('nombre', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
