# Generated by Django 4.1.6 on 2023-04-17 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_carrito'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='carrito',
            new_name='carritos',
        ),
    ]
